name: Lint, build, and test
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install npm dependencies
        run: npm install
      - name: Run linter
        run: npm run lint-check
      - name: Run TypeScript compiler
        run: npm run build
      - name: Run tests
        run: npm test
